language: node_js
node_js:
  - "4.2"

#rethinkdb support for travis [figure this out later]:
#https://github.com/neumino/reqlite/blob/master/.travis.yml
#https://www.google.ca/search?q=%23+-+source+%2Fetc%2Flsb-release+%26%26+echo+%22deb+http%3A%2F%2Fdownload.rethinkdb.com%2Fapt+%24DISTRIB_CODENAME+main%22+%7C+sudo+tee+%2Fetc%2Fapt%2Fsources.list.d%2Frethinkdb.list&oq=%23+-+source+%2Fetc%2Flsb-release+%26%26+echo+%22deb+http%3A%2F%2Fdownload.rethinkdb.com%2Fapt+%24DISTRIB_CODENAME+main%22+%7C+sudo+tee+%2Fetc%2Fapt%2Fsources.list.d%2Frethinkdb.list&aqs=chrome..69i57.201j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=travis+%23+-+source+%2Fetc%2Flsb-release+%26%26+echo+%22deb+http:%2F%2Fdownload.rethinkdb.com%2Fapt+%24DISTRIB_CODENAME+main%22+%7C+sudo+tee+%2Fetc%2Fapt%2Fsources.list.d%2Frethinkdb.list

#before_install:
#  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
#  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
#  - sudo apt-get update -q
#  - sudo apt-get install rethinkdb
#  - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
#  - sudo service rethinkdb restart

#services
# - rethinkdb

before_script:
 - npm install -g gulp
script: gulp